### ISSUE TITLE
ask for your help about your "nabor" package

### ISSUE THREAD

**Issue by qiucoolcool** [jefferis/nabor#10]
Hi. your r package nabor is really helpful. But recently I encountered a problem. After I construct the big kd-tree for the whole dataset, how to extract a small kd-tree (for a sub-dataset of the whole dataset) from the original big kd-tree? in other words, how to deletes some nodes from the big kd-tree? (this could accelerate the searching process, since the deleted nodes are the ones that I am 100% sure to be not the k nearest samples,) Many Thank for your help! Best wishes.

**Comment by jefferis** [comment]
For reference, this is not possible unfortunately. The only way would be to build a fresh tree.

**Comment by qiucoolcool** [comment]
Thank you so much for your kind reply. Best wishes.
